# Generated by Django 2.2.4 on 2019-11-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191126_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('percent_off_deal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
