# Generated by Django 2.2.4 on 2019-11-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_featured_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_down_ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(blank=True, help_text='image size must be : 321 x 450', upload_to='ads')),
                ('img_1', models.ImageField(blank=True, help_text='image size must be : 123 x 127', upload_to='ads')),
                ('img_2', models.ImageField(blank=True, help_text='image size must be : 123 x 127', upload_to='ads')),
                ('img_3', models.ImageField(blank=True, help_text='image size must be : 123 x 127', upload_to='ads')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='featured_ads',
            name='image',
            field=models.ImageField(blank=True, upload_to='ads'),
        ),
    ]
