# Generated by Django 2.2.4 on 2019-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191127_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_down_ads',
            old_name='main_image',
            new_name='main_image_slide1',
        ),
        migrations.AddField(
            model_name='count_down_ads',
            name='main_image_slide2',
            field=models.ImageField(blank=True, help_text='image size must be : 321 x 450', upload_to='ads'),
        ),
        migrations.AddField(
            model_name='count_down_ads',
            name='main_image_slide3',
            field=models.ImageField(blank=True, help_text='image size must be : 321 x 450', upload_to='ads'),
        ),
    ]
