# Generated by Django 2.2.4 on 2019-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='logo')),
                ('image_two', models.ImageField(blank=True, upload_to='logo')),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
