# Generated by Django 2.2.4 on 2019-11-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_landing_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landing_products',
        ),
    ]
